name: Lint, build and test the app
run-name: ${{ github.actor }}
on: [push]
jobs:
  Lint-Build-Test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run test